Croatia_Provinces = {
    '01': 'Zagreb',
    '02': 'Krapina-Zagorje',
    '03': 'Sisak-Moslavina',
    '04': 'Karlovac',
    '05': 'Varaždin',
    '06': 'Koprivnica-Križevci',
    '07': 'Bjelovar-Bilogora',
    '08': 'Primorje-Gorski Kotar',
    '09': 'Lika-Senj',
    '10': 'Virovitica-Podravina',
    '11': 'Požega-Slavonia',
    '12': 'Brodsko-Posavska',
    '13': 'Zadar',
    '14': 'Osijek-Baranja',
    '15': 'Šibenik-Knin',
    '16': 'Vukovar-Srijem',
    '17': 'Split-Dalmatia',
    '18': 'Istria',
    '19': 'Dubrovnik-Neretva'
}