Finland_Provinces = {
        'Ahvenanmaa': 'Åland',
        'Etelä-Karjala': 'South Karelia',
        'Etelä-Pohjanmaa': 'Southern Ostrobothnia',
        'Etelä-Savo': 'South Savo',
        'Kainuu': 'Kainuu',
        'Kanta-Häme': 'Tavastia Proper',
        'Keski-Pohjanmaa': 'Central Ostrobothnia',
        'Keski-Suomi': 'Central Finland',
        'Kymenlaakso': 'Kymenlaakso',
        'Lappi': 'Lapland',
        'Pirkanmaa': 'Tavastia Proper',
        'Pohjanmaa': 'Ostrobothnia',
        'Pohjois-Karjala': 'North Karelia',
        'Pohjois-Pohjanmaa': 'Northern Ostrobothnia',
        'Pohjois-Savo': 'North Savo',
        'Päijät-Häme': 'Päijänne Tavastia',
        'Satakunta': 'Satakunta',
        'Uusimaa': 'Uusimaa',
        'Varsinais-Suomi': 'Southwest Finland',
    }