France_Provinces = {
  "Alsace": "Strasbourg",
  "Aquitaine": "Bordeaux",
  "Auvergne": "Clermont-Ferrand",
  "Basse-Normandie": "Caen",
  "Bourgogne": "Dijon",
  "Bretagne": "Rennes",
  "Centre": "Orléans",
  "Champagne-Ardenne": "Reims",
  "Corse": "Ajaccio",
  "Franche-Comté": "Besançon",
  "Haute-Normandie": "Rouen",
  "Île-de-France": "Paris",
  "Languedoc-Roussillon": "Montpellier",
  "Limousin": "Limoges",
  "Lorraine": "Metz",
  "Midi-Pyrénées": "Toulouse",
  "Nord-Pas-de-Calais": "Lille",
  "Pays de la Loire": "Nantes",
  "Picardie": "Amiens",
  "Poitou-Charentes": "Poitiers",
  "Provence-Alpes-Côte d'Azur": "Marseille",
  "Rhône-Alpes": "Lyon"
}