Italy_Provinces = {
    'Valle d Aosta': 'Aosta',
    'Piemonte': 'Torino' ,
    'Lombardia': 'Milano',
    'Veneto': 'Venezia',
    'Trentino-Alto Adige': 'Trento',
    'Friuli-Venezia Giulia': 'Trieste',
    'Liguria': 'Genova',
    'Emilia-Romagna': 'Bologna',
    'Toscana': 'Firenze',
    'Umbria': 'Perugia',
    'Marche': 'Ancona',
    'Abruzzo': 'L Aquila',
    'Molise': 'Campobasso',
    'Campania': 'Napoli',
    'Puglia': 'Bari',
    'Basilicata': 'Potenza',
    'Calabria': 'Catanzaro',
    'Sicilia': 'Palermo',
    'Sardegna': 'Cagliari',
}