
Malta_Provinces = {
    'MT-01': 'Attard',
    'MT-02': 'Balzan',
    'MT-03': 'Birgu',
    'MT-04': 'Birkirkara',
    'MT-05': 'Birzebbuga',
    'MT-06': 'Bormla',
    'MT-07': 'Dingli',
    'MT-08': 'Fgura',
    'MT-09': 'Floriana',
    'MT-10': 'Fontana',
    'MT-11': 'Gudja',
    'MT-12': 'Gzira',
    'MT-13': 'Gargur',
    'MT-14': 'Gaxaq',
    'MT-15': 'Hamrun',
    'MT-16': 'Iklin',
    'MT-17': 'Isla',
    'MT-18': 'Kalkara',
    'MT-19': 'Kercem',
    'MT-20': 'Kirkop',
    'MT-21': 'Lija',
    'MT-22': 'Luqa',
    'MT-23': 'Marsa',
    'MT-24': 'Marsaskala',
    'MT-25': 'Marsaxlokk',
    'MT-26': 'Mdina',
    'MT-27': 'Melliea',
    'MT-28': 'Mgarr',
    'MT-29': 'Mosta',
    'MT-30': 'Mqabba',
    'MT-31': 'Msida',
    'MT-32': 'Mtarfa',
    'MT-33': 'Munxar',
    'MT-34': 'Nadur',
    'MT-35': 'Naxxar',
    'MT-36': 'Paola',
    'MT-37': 'Pembroke',
    'MT-38': 'Pieta',
    'MT-39': 'Qala',
    'MT-40': 'Qormi',
    'MT-41': 'Qrendi',
    'MT-42': 'Rabat',
    'MT-43': 'Safi',
    'MT-44': 'San Giljan',
    'MT-45': 'San Gwann',
    'MT-46': 'San Lawrenz',
    'MT-47': 'San Pawl il-Bahar',
    'MT-48': 'Sannat',
    'MT-49': 'Santa Lucija',
    'MT-50': 'Santa Venera',
    'MT-51': 'Siggiewi',
    'MT-52': 'Sliema',
    'MT-53': 'Swieqi',
    'MT-54': 'Ta Xbiex',
    'MT-55': 'Tarxien',
    'MT-56': 'Valletta',
    'MT-57': 'Xagra',
    'MT-58': 'Xewkija',
    'MT-59': 'Xghajra',
    'MT-60': 'Zabbar',
    'MT-61': 'Zebbug',
    'MT-62': 'Zejtun',
    'MT-63': 'Zurrieq',
}